/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cone: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export function TriangleSolid({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    "/models/TriangleSolid2.glb"
  ) as GLTFResult;

  return (
    <group name={"triangle_solid"} ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cone.geometry}
        material={materials["Material.001"]}
        position={[0, 4.85, 0]}
        scale={[1.87, 1.31, 1.87]}
      />
    </group>
  );
}

useGLTF.preload("/models/TriangleSolid2.glb");
